name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  backup-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install lftp
      

      - name: Set backup folder name with date
        id: set_backup
        run: echo "BACKUP_FOLDER=backup_$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
     
      - name: Download /pub folder from FTP server to runner
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
            set ssl:verify-certificate no;            
            mirror --verbose --exclude backup /pub ./backup/${{ env.BACKUP_FOLDER }};
            bye
          "

      - name: List downloaded backup files
        run: ls -R ./


      - name: Upload backup to FTP server as dated backup folder
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
            set ssl:verify-certificate no;
            set cmd:trace true;
            set xfer:clobber on;
            mkdir -p /backup/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
            ls /backup;
            mirror --reverse --verbose ./backup/${{ env.BACKUP_FOLDER }} /backup/${{ env.BACKUP_FOLDER }};
            bye
          "

      - name: Deploy latest build to /pub folder on FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./pub/
          protocol: ftp
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            backup/**
            web.config
