name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  backup-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install lftp

      # - name: List all directories in root folder of FTP server
      #   run: |
      #     lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
      #       set ssl:verify-certificate no;
      #       cls -l;
      #       bye
      #     "

      - name: Set backup folder name with date
        id: set_backup
        run: echo "BACKUP_FOLDER=backup_$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Backup existing /pub folder on FTP server to /backup_YYYYMMDD, excluding backup folders
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
            set ssl:verify-certificate no;
            mkdir -p /pub || echo 'Directory /pub already exists or cannot be created';
            mkdir -p /pub/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
            chmod 777 /pub;
            chmod 777 /pub/${{ env.BACKUP_FOLDER }};
            bye
          "
      - name: Wait for backup folder creation
        run: sleep 10

      - name: Mirror /pub to backup folder, excluding backup folders
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
            set ssl:verify-certificate no;
            mirror --verbose --exclude-glob pub/backup_* /pub /pub/${{ env.BACKUP_FOLDER }};
            bye
          "

      - name: Deploy latest build to /pub folder on FTP server
        run: |
          lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
            set ssl:verify-certificate no;
            mirror --reverse --delete --verbose ./ ./pub/;
            bye
          "